import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { X, Calendar, Clock, MapPin, AlertCircle, CheckCircle, Lock, Users, Star, Globe, Building } from 'lucide-react';
import {
    eventService,
    EventType,
    EventStatus,
    EventMode,  // ✅ NEW - Import EventMode
    EventTypeLabels,
    EventModeLabels,  // ✅ NEW - Import EventModeLabels
    type EventCreateDto
} from '../../services/eventService';
import { ActivityType, ActivityTypeLabels } from '../../services/teamService';
import { teacherService, type Teacher } from '../../services/teacherService';
import { getTranslatedActivityType } from '../../utils/activityTypeTranslations';
import { getTranslatedEventType } from '../../utils/eventTypeTranslations';
import { useAuth } from '../../hooks/useAuth';

interface AddEventModalProps {
    onClose: () => void;
    onSuccess: () => void;
}

const AddEventModal = ({ onClose, onSuccess }: AddEventModalProps) => {
    const { t } = useTranslation();
    const { user } = useAuth();
    const [loading, setLoading] = useState(false);
    const [teachers, setTeachers] = useState<Teacher[]>([]);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState(false);

    // Track if the current user is a teacher and their teacherID
    const [currentUserTeacherId, setCurrentUserTeacherId] = useState<number | null>(null);
    const isTeacherRole = user?.userRole === 'Teacher';

    // State for multiple teachers
    const [selectedTeacherIds, setSelectedTeacherIds] = useState<number[]>([]);
    const [primaryTeacherId, setPrimaryTeacherId] = useState<number | null>(null);

    // ✅ UPDATED: Added eventMode with default Offline
    const [formData, setFormData] = useState<EventCreateDto>({
        eventName: '',
        eventCode: '',
        eventType: EventType.Training,
        activityType: ActivityType.Football,
        status: EventStatus.Planned,
        eventMode: EventMode.Offline,  // ✅ NEW - Default to Offline
        eventDate: new Date().toISOString().split('T')[0],
        endDate: undefined,
        startTime: '08:00',
        venue: '',  // ✅ Now optional
        requiresParentConsent: false,
        result: '',
        awardsReceived: '',
        remarks: ''
    });

    useEffect(() => {
        loadData();
    }, []);

    useEffect(() => {
        if (success) {
            const timer = setTimeout(() => {
                onSuccess();
            }, 2000);

            return () => {
                clearTimeout(timer);
            };
        }
    }, [success, onSuccess]);

    const loadData = async () => {
        try {
            const teachersData = await teacherService.getAllTeachers(true);
            setTeachers(teachersData);

            // If user is a Teacher, auto-select them and mark as primary
            if (isTeacherRole && user?.userId) {
                const currentTeacher = teachersData.find(
                    (teacher) => teacher.userID === user.userId
                );

                if (currentTeacher) {
                    setCurrentUserTeacherId(currentTeacher.teacherID);
                    // Auto-select current teacher
                    setSelectedTeacherIds([currentTeacher.teacherID]);
                    setPrimaryTeacherId(currentTeacher.teacherID);
                }
            }
        } catch (error) {
            console.error('Error loading data:', error);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);

        // Validation
        if (!formData.eventName.trim()) {
            setError(t('events.addModal.validation.eventNameRequired'));
            return;
        }

        // ✅ Event Code is now auto-generated by backend

        // ✅ Venue is now completely optional for both Online and Offline events

        // Validate at least one teacher is selected
        if (selectedTeacherIds.length === 0) {
            setError(t('events.addModal.validation.teacherRequired') || 'Please select at least one teacher');
            return;
        }

        try {
            setLoading(true);

            // Prepare form data with teacher assignments
            const submitData: EventCreateDto = {
                ...formData,
                teacherIDs: selectedTeacherIds,
                primaryTeacherID: primaryTeacherId || selectedTeacherIds[0]
            };

            await eventService.createEvent(submitData);
            setLoading(false);
            setSuccess(true);

        } catch (error) {
            setLoading(false);
            console.error('Error creating event:', error);

            if (error && typeof error === 'object' && 'response' in error) {
                const axiosError = error as { response?: { data?: unknown; status?: number } };
                console.error('Response data:', axiosError.response?.data);
                console.error('Response status:', axiosError.response?.status);
            }

            const errorMessage = error instanceof Error && 'response' in error
                ? (error as { response?: { data?: { message?: string } } }).response?.data?.message
                : t('events.addModal.messages.errorCreating');
            setError(errorMessage || t('events.addModal.messages.errorCreating'));
        }
    };

    const handleChange = <K extends keyof EventCreateDto>(field: K, value: EventCreateDto[K]) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    // Toggle teacher selection
    const toggleTeacherSelection = (teacherId: number) => {
        if (isTeacherRole && teacherId !== currentUserTeacherId) {
            return;
        }

        setSelectedTeacherIds(prev => {
            if (prev.includes(teacherId)) {
                const newSelection = prev.filter(id => id !== teacherId);
                if (primaryTeacherId === teacherId) {
                    setPrimaryTeacherId(newSelection.length > 0 ? newSelection[0] : null);
                }
                return newSelection;
            } else {
                const newSelection = [...prev, teacherId];
                if (newSelection.length === 1) {
                    setPrimaryTeacherId(teacherId);
                }
                return newSelection;
            }
        });
    };

    // Set primary teacher
    const handleSetPrimaryTeacher = (teacherId: number) => {
        if (selectedTeacherIds.includes(teacherId)) {
            setPrimaryTeacherId(teacherId);
        }
    };

    // Get the current teacher's name for display when locked
    const getCurrentTeacherName = (): string => {
        if (currentUserTeacherId) {
            const teacher = teachers.find(t => t.teacherID === currentUserTeacherId);
            return teacher?.fullName || '';
        }
        return '';
    };

    // ✅ NEW - Helper function to get translated event mode label
    const getTranslatedEventMode = (mode: EventMode): string => {
        const modeKey = mode === EventMode.Online ? 'online' : 'offline';
        return t(`events.eventMode.${modeKey}`) || EventModeLabels[mode];
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
                {/* Header with Success Alert */}
                <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center z-10 shadow-sm">
                    <div className="flex items-center gap-4 flex-1 min-w-0">
                        <h2 className="text-xl font-bold text-gray-900 flex-shrink-0">{t('events.addModal.title')}</h2>

                        {/* Success Alert in Header */}
                        {success && (
                            <div className="flex items-center gap-2 px-4 py-2 bg-green-50 border-2 border-green-500 rounded-lg shadow-lg">
                                <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0" />
                                <div className="flex-1 min-w-0">
                                    <p className="text-sm font-semibold text-green-900 whitespace-nowrap">{t('events.addModal.messages.successCreated')}</p>
                                    <p className="text-xs text-green-700 whitespace-nowrap">{t('events.addModal.messages.closingIn')}</p>
                                </div>
                            </div>
                        )}
                    </div>

                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 transition-colors flex-shrink-0 ml-4"
                        disabled={loading || success}
                    >
                        <X className="w-6 h-6" />
                    </button>
                </div>

                {/* Form */}
                <form onSubmit={handleSubmit} className="p-6">
                    {/* Error Alert */}
                    {error && !success && (
                        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
                            <AlertCircle className="w-5 h-5 text-red-500 mt-0.5 flex-shrink-0" />
                            <p className="text-sm text-red-700">{error}</p>
                        </div>
                    )}

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Basic Information */}
                        <div className="md:col-span-2">
                            <h3 className="text-lg font-semibold text-gray-900 mb-4">{t('events.addModal.sections.basicInfo')}</h3>
                        </div>

                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.eventName')} *
                            </label>
                            <input
                                type="text"
                                value={formData.eventName}
                                onChange={(e) => handleChange('eventName', e.target.value)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                placeholder={t('events.addModal.placeholders.eventName')}
                                required
                                disabled={loading || success}
                            />
                        </div>

                        {/* Event Type */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.eventType')} *
                            </label>
                            <select
                                value={formData.eventType}
                                onChange={(e) => handleChange('eventType', Number(e.target.value) as EventType)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                                disabled={loading || success}
                            >
                                {Object.entries(EventTypeLabels).map(([key, label]) => (
                                    <option key={key} value={key}>
                                        {getTranslatedEventType(label, t)}
                                    </option>
                                ))}
                            </select>
                        </div>

                        {/* Activity Type */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.activityType')} *
                            </label>
                            <select
                                value={formData.activityType}
                                onChange={(e) => handleChange('activityType', Number(e.target.value) as ActivityType)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                                disabled={loading || success}
                            >
                                {Object.entries(ActivityTypeLabels).map(([key, label]) => (
                                    <option key={key} value={key}>
                                        {getTranslatedActivityType(label, t)}
                                    </option>
                                ))}
                            </select>
                        </div>

                        {/* ✅ NEW - Event Mode (Online/Offline) */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {formData.eventMode === EventMode.Online ? (
                                    <Globe className="w-4 h-4 inline mr-2 text-cyan-600" />
                                ) : (
                                    <Building className="w-4 h-4 inline mr-2 text-purple-600" />
                                )}
                                {t('events.addModal.fields.eventMode') || 'Event Mode'} *
                            </label>
                            <select
                                value={formData.eventMode}
                                onChange={(e) => handleChange('eventMode', Number(e.target.value) as EventMode)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                                disabled={loading || success}
                            >
                                <option value={EventMode.Offline}>
                                    {getTranslatedEventMode(EventMode.Offline)}
                                </option>
                                <option value={EventMode.Online}>
                                    {getTranslatedEventMode(EventMode.Online)}
                                </option>
                            </select>
                            {/*<p className="text-xs text-gray-500 mt-1">*/}
                            {/*    {formData.eventMode === EventMode.Online*/}
                            {/*        ? (t('events.addModal.helpers.eventModeOnline') || 'Virtual event - venue is optional')*/}
                            {/*        : (t('events.addModal.helpers.eventModeOffline') || 'Physical event - venue is required')*/}
                            {/*    }*/}
                            {/*</p>*/}
                        </div>

                        {/* Multiple Teachers Selection */}
                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                <Users className="w-4 h-4 inline mr-2" />
                                {t('events.addModal.fields.leadingTeacher') || 'Assigned Teachers'} *
                                {isTeacherRole && currentUserTeacherId && (
                                    <Lock className="w-4 h-4 inline ml-2 text-gray-400" />
                                )}
                            </label>

                            {/* Show locked display for Teacher role */}
                            {isTeacherRole && currentUserTeacherId ? (
                                <div className="p-4 bg-gray-50 border border-gray-300 rounded-lg">
                                    <div className="flex items-center gap-2">
                                        <Star className="w-5 h-5 text-yellow-500 fill-yellow-500" />
                                        <span className="font-medium text-gray-900">{getCurrentTeacherName()}</span>
                                        <span className="text-xs text-gray-500 ml-2">
                                            ({t('events.addModal.labels.primaryTeacher') || 'Primary Teacher'})
                                        </span>
                                    </div>
                                    <p className="text-xs text-gray-500 mt-2">
                                        {t('events.addModal.messages.teacherAutoSelected') || 'You are automatically assigned as the primary teacher'}
                                    </p>
                                </div>
                            ) : (
                                /* Multiple teacher selection for Admin/SuperAdmin */
                                <div className="border border-gray-300 rounded-lg max-h-64 overflow-y-auto">
                                    {teachers.length === 0 ? (
                                        <div className="p-4 text-center text-gray-500">
                                            {t('events.addModal.messages.noTeachers') || 'No teachers available'}
                                        </div>
                                    ) : (
                                        <div className="divide-y divide-gray-200">
                                            {teachers.map((teacher) => {
                                                const isSelected = selectedTeacherIds.includes(teacher.teacherID);
                                                const isPrimary = primaryTeacherId === teacher.teacherID;

                                                return (
                                                    <div
                                                        key={teacher.teacherID}
                                                        className={`p-3 hover:bg-gray-50 transition-colors ${isSelected ? 'bg-blue-50' : ''
                                                            }`}
                                                    >
                                                        <div className="flex items-center gap-3">
                                                            <input
                                                                type="checkbox"
                                                                checked={isSelected}
                                                                onChange={() => toggleTeacherSelection(teacher.teacherID)}
                                                                disabled={loading || success}
                                                                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
                                                            />

                                                            <div className="flex-1 min-w-0">
                                                                <div className="flex items-center gap-2">
                                                                    <span className={`font-medium ${isSelected ? 'text-blue-900' : 'text-gray-900'
                                                                        }`}>
                                                                        {teacher.fullName}
                                                                    </span>
                                                                    {isPrimary && (
                                                                        <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-yellow-100 text-yellow-800 text-xs font-medium rounded-full">
                                                                            <Star className="w-3 h-3 fill-yellow-500" />
                                                                            {t('events.addModal.labels.primary') || 'Primary'}
                                                                        </span>
                                                                    )}
                                                                </div>
                                                                {teacher.email && (
                                                                    <p className="text-xs text-gray-500 truncate">
                                                                        {teacher.email}
                                                                    </p>
                                                                )}
                                                            </div>

                                                            {isSelected && !isPrimary && (
                                                                <button
                                                                    type="button"
                                                                    onClick={() => handleSetPrimaryTeacher(teacher.teacherID)}
                                                                    disabled={loading || success}
                                                                    className="text-xs text-blue-600 hover:text-blue-800 font-medium"
                                                                    title={t('events.addModal.buttons.setPrimary') || 'Set as primary'}
                                                                >
                                                                    {t('events.addModal.buttons.setPrimary') || 'Set Primary'}
                                                                </button>
                                                            )}
                                                        </div>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    )}
                                </div>
                            )}

                            {/* Selected teachers summary */}
                            {!isTeacherRole && selectedTeacherIds.length > 0 && (
                                <p className="mt-2 text-sm text-gray-600">
                                    {t('events.addModal.messages.teachersSelected') || 'Selected'}: {selectedTeacherIds.length} {t('events.addModal.labels.teachers') || 'teacher(s)'}
                                </p>
                            )}
                        </div>

                        {/* Date & Time */}
                        <div className="md:col-span-2">
                            <h3 className="text-lg font-semibold text-gray-900 mb-4 mt-4">
                                {t('events.addModal.sections.dateTime')}
                            </h3>
                        </div>

                        {/* Start Date */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                <Calendar className="w-4 h-4 inline mr-2" />
                                {t('events.addModal.fields.startDate') || 'Start Date'} *
                            </label>
                            <input
                                type="date"
                                value={formData.eventDate}
                                onChange={(e) => handleChange('eventDate', e.target.value)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                                disabled={loading || success}
                            />
                        </div>

                        {/* End Date (Optional) */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                <Calendar className="w-4 h-4 inline mr-2" />
                                {t('events.addModal.fields.endDate') || 'End Date'}
                                <span className="text-xs text-gray-500 ml-1">
                                    ({t('events.addModal.labels.optional') || 'Optional'})
                                </span>
                            </label>
                            <input
                                type="date"
                                value={formData.endDate || ''}
                                onChange={(e) => handleChange('endDate', e.target.value || undefined)}
                                min={formData.eventDate}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                disabled={loading || success}
                            />
                            <p className="text-xs text-gray-500 mt-1">
                                {t('events.addModal.helpers.endDate') || 'Leave blank for single-day events. Select a date for multi-day events.'}
                            </p>
                        </div>

                        {/* Start Time */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                <Clock className="w-4 h-4 inline mr-2" />
                                {t('events.addModal.fields.startTime')} *
                            </label>
                            <input
                                type="time"
                                value={formData.startTime}
                                onChange={(e) => handleChange('startTime', e.target.value)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                required
                                disabled={loading || success}
                            />
                        </div>

                        {/* End Time (Optional) */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                <Clock className="w-4 h-4 inline mr-2" />
                                {t('events.addModal.fields.endTime')}
                            </label>
                            <input
                                type="time"
                                value={formData.endTime || ''}
                                onChange={(e) => handleChange('endTime', e.target.value || undefined)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                disabled={loading || success}
                            />
                        </div>

                        {/* Location */}
                        <div className="md:col-span-2">
                            <h3 className="text-lg font-semibold text-gray-900 mb-4 mt-4">{t('events.addModal.sections.location')}</h3>
                        </div>

                        {/* ✅ UPDATED - Venue is now completely optional */}
                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                <MapPin className="w-4 h-4 inline mr-2" />
                                {t('events.addModal.fields.venue')}
                                <span className="text-xs text-gray-500 ml-1">
                                    ({t('events.addModal.labels.optional') || 'Optional'})
                                </span>
                            </label>
                            <input
                                type="text"
                                value={formData.venue || ''}
                                onChange={(e) => handleChange('venue', e.target.value)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                placeholder={
                                    formData.eventMode === EventMode.Online
                                        ? (t('events.addModal.placeholders.venueOnline') || 'e.g., Zoom, Google Meet, Microsoft Teams')
                                        : t('events.addModal.placeholders.venue')
                                }
                                disabled={loading || success}
                            />
                            {formData.eventMode === EventMode.Online && (
                                <p className="text-xs text-gray-500 mt-1">
                                    {t('events.addModal.helpers.venueOnline') || 'For online events, you can specify the platform name or meeting link'}
                                </p>
                            )}
                        </div>

                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.venueAddress')}
                            </label>
                            <input
                                type="text"
                                value={formData.venueAddress || ''}
                                onChange={(e) => handleChange('venueAddress', e.target.value || undefined)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                placeholder={
                                    formData.eventMode === EventMode.Online
                                        ? (t('events.addModal.placeholders.venueAddressOnline') || 'e.g., Meeting URL or access instructions')
                                        : t('events.addModal.placeholders.venueAddress')
                                }
                                disabled={loading || success}
                            />
                        </div>

                        {/* Additional Information */}
                        <div className="md:col-span-2">
                            <h3 className="text-lg font-semibold text-gray-900 mb-4 mt-4">{t('events.addModal.sections.additionalInfo')}</h3>
                        </div>

                        {/* Result */}
                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.result')}
                            </label>
                            <input
                                type="text"
                                value={formData.result || ''}
                                onChange={(e) => handleChange('result', e.target.value || undefined)}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                placeholder={t('events.addModal.placeholders.result')}
                                disabled={loading || success}
                            />
                        </div>

                        {/* Awards Received */}
                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.awardsReceived')}
                            </label>
                            <textarea
                                value={formData.awardsReceived || ''}
                                onChange={(e) => handleChange('awardsReceived', e.target.value || undefined)}
                                rows={3}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                placeholder={t('events.addModal.placeholders.awardsReceived')}
                                disabled={loading || success}
                            />
                        </div>

                        {/* Remarks / Suggestions */}
                        <div className="md:col-span-2">
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                {t('events.addModal.fields.remarks')}
                            </label>
                            <textarea
                                value={formData.remarks || ''}
                                onChange={(e) => handleChange('remarks', e.target.value || undefined)}
                                rows={3}
                                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                placeholder={t('events.addModal.placeholders.remarks')}
                                disabled={loading || success}
                            />
                        </div>
                    </div>

                    {/* Footer Buttons */}
                    <div className="flex justify-end gap-3 mt-6 pt-6 border-t border-gray-200">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
                            disabled={loading || success}
                        >
                            {t('events.addModal.buttons.cancel')}
                        </button>
                        <button
                            type="submit"
                            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed transition-colors"
                            disabled={loading || success}
                        >
                            {loading ? t('events.addModal.buttons.creating') : success ? t('events.addModal.buttons.created') : t('events.addModal.buttons.create')}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default AddEventModal;